### ISSUE TITLE
requestFrame('cancel') on IE9

### ISSUE THREAD

**Issue by rPennacchio** [julienetie/request-frame#1]
Hi Julien,
I'm on IE9 and I want to cancel a loop created by requestFrame('request') and the script seems to not cancel the loop.
This browser have the method Array.prototype.map so clearTimeout is never fired...

Romain.

**Comment by julienetie** [comment]
Hi Romain

Thanks for opening this issue. The Array.prototype.map condition results to undefined, which eventually triggers clearTimeoutWithId() when prefixedCancelAnimationFrame is called. Looks like clearTimeoutWithId was missing a parameter for clearTimeout. I've corrected this now and bumped the version.

Let me know if this is working for you.

Julien

**Comment by rPennacchio** [comment]
Hi Julien,
You're fix works fine, thanks !

Romain.

**Comment by julienetie** [comment]
Great, thanks for the update.
