### ISSUE TITLE
` on iOS6 notice is causing build to fail on heroku

### ISSUE THREAD

**Issue by Daven-** [julienetie/request-frame#10]
`const iOS6Notice = \` setTimeout is being used as a substitiue for requestAnimationFrame due to a bug within iOS 6 builds`; `

I propose changing it back from backticks to single quotes?

**Comment by julienetie** [comment]
Hi Daven
This was due to the incorrect babel preset, 
This is now fixed (1.5.2 release), request-frame.js is now in ES5. 
Closing this issue as it relates to https://github.com/julienetie/request-frame/issues/9

**Comment by Daven-** [comment]
shoot! didn't really read that issue, sorry.

**Comment by julienetie** [comment]
No harm at all, totally my mistake tbh.
