### ISSUE TITLE
Tag a Release

### ISSUE THREAD

**Issue by ptlis** [julienetie/request-frame#3]
The README suggests that there is a 1.0.2 release, but I see no such tag and you cannot target this version number in bower.

It would be nicer if we could target a (stable) version.

**Comment by ptlis** [comment]
Actually, it looks like the release number hasn't been updated in the bower.json file - it's currently set to 0.8.1 rather than 1.0.2 in the package.json.

**Comment by julienetie** [comment]
Thanks, I just added gulp-bump to fix this, and bumped it to 1.0.3.

**Comment by hppycoder** [comment]
Sorry to rehash this issue, but can you tell GitHub about the release? That way when Bower has something to compare it to it will find it. Right now it's technically 1.4.1, however since there's no actual "Releases" Bower can't pull because there's no tags on the repo.

**Comment by julienetie** [comment]
Thanks, I kind of overlooked the tag. It should be working with Bower now, but please hit me up if there's any more issues.
