### ISSUE TITLE
ReferenceError: screen is not defined

### ISSUE THREAD

**Issue by binarykitchen** [julienetie/request-frame#6]
When I run mocha tests on server side, I get the above error.

I know it does not make sense on server side but could you at least shim `screen`?

**Comment by julienetie** [comment]
Possibly "screen.xx" as "window.screen.xx" may resolve the Issue, unless you have a better solution. I'll test it out shortly.

**Comment by binarykitchen** [comment]
yes, please, thanks. either shim or polyfill or just do something like

```
if ('undefined' != typeof screen) {
    // your code here
}
```

**Comment by julienetie** [comment]
The test are not set up for node, only just realized (been a while, sorry about that). The test runner is test.html. As this plugin is only a necessary for the browser it should be sufficient.
