### ISSUE TITLE
Error in docs (README.md)

### ISSUE THREAD

**Issue by gpetrioli** [julienetie/request-frame#7]
In the "Loop something" section in the docs shouldn't the `request(something)` call from inside the `something` function get re-assigned to the `requestId` variable, so it can be cancelled later on ?

So

```
function something( useTimeStamp ){
    // Do something here
    request(something); 
}

var requestId = request(something); // Assigns Id & calls "something"
```

should become

```
var requestId;

function something( useTimeStamp ){
    // Do something here
   requestId = request(something); 
}

requestId = request(something); // Assigns Id & calls "something"
```

**Comment by julienetie** [comment]
Thanks Gabriele, I'll correct this on the next release.
