### ISSUE TITLE
Possible to transpile to ES5 for publishing to npm?

### ISSUE THREAD

**Issue by robations** [julienetie/request-frame#9]
I see in the latest version there is an `interpolated string` in the project that has been playing havoc with our build system. Is there a possibility of using a transpiler as part of your package/publish system, or replacing this line with a traditional string?

Maybe this was just a mistake, but if not I will stick to an older version until I can set up transpiling in my project.

**Comment by julienetie** [comment]
Hi Robert
Yes this was a mistake due to an incorrect rollup babel preset. 
This has now been resolved (bumped to 1.5.2),
request-frame.js is now es5 and has been tested in a non-es6 environment.

**Comment by robations** [comment]
Thanks for the fix, and the project!

**Comment by julienetie** [comment]
Much appreciated Robert. Thanks for reporting the issue and using it ;-)
